version: '3.7'
services:
  speed-splits:
    build:
      context: .
    image: speed-splits
    volumes:
      - /speed-splits/volume/logs:/etc/speed-splits/logs
    ports:
      - "14444:5000"
    restart: unless-stopped
