version: '3.7'
services:
  speed-splits:
    build:
      context: .
    image: speeds-splits
    volumes:
      - split-compare/volume/logs:/etc/speed-splits/logs
    ports:
      - "5000:5000"
    restart: unless-stopped
